### PR TITLE
Implement basic event manipulation operations in the map editor

### PR DESCRIPTION
**Pull request by white-axe**
I added a more user-friendly system for selecting a specific event on the map. When the event layer is selected in the layer dropdown, the selected event is chosen from multiple candidates (which can be changed if need be) with the following priority:

1. If a shift key is held down, no event
2. Otherwise, the unique event whose tile is hovered over by the mouse, if it exists
3. Otherwise, the event with the highest ID whose graphic contains the pixel the mouse is hovering over, if it exists
4. Otherwise, the unique event whose tile is selected on the map, if it exists
5. Otherwise, the event with the highest ID whose graphic contains the pixel in the center of the tile selected on the map, if it exists
6. Otherwise, no event

Using this system, this pull request implements various methods of interacting with events on the map:

- Adds the ability to open the event editor window on an existing event by selecting it and then double-clicking with the primary mouse button or pressing enter
- Adds the ability to create a new event by doing the same while no event is selected, with a check to make sure you can't create an event on a tile that already has one
- Adds the ability to delete an event by selecting it and then pressing delete or backspace
- Adds the ability to move an event on the map by selecting it and then dragging and dropping it with the primary mouse button, with a check to make sure you can't move the event so that its tile is also the tile of another event

I didn't make any changes to the actual event editor window, though. I just wanted to put these basic features into a pull request first.

### CODE REVIEW

**Comment by Speak2Erase** [comment]
I can't seem to make or open events in the event editor, but I can delete events

**Comment by white-axe** [comment]
Does it work when you select an event and then press enter?

**Comment by Speak2Erase** [comment]
Nevermind, git was being weird

**Review by Speak2Erase — CHANGES_REQUESTED** [review]
Okay, a couple weird UX issues:
image
There are a lot of highlights around events at the same time, which can look pretty weird (especially on 32x32 events)

luminol_apg24zfLRF
Opening events keeps them being dragged to your cursor, which is annoying

**Comment by white-axe** [comment]
Do you have any suggestions for how the highlighting should be performed?

**Comment by Speak2Erase** [comment]
- Highlight the event as yellow if it is hovered over and double clicking/pressing enter would open the event editor
- Highlight the event as pink or green if it is being edited

**Comment by Speak2Erase** [comment]
As for the event editor, I was hoping to get new-tilemap to an mvp state (which it's pretty close to, I think? The only thing it's missing is multiple brushes and drawing rectangles of tiles) and merge it, then refactor Luminol a bit (like splitting it into multiple crates) before tackling the event editor

**Review by Speak2Erase — APPROVED** [review]

**Pull request merged**
