### PR TITLE
Use color-eyre for error handling and add a log window

### LINKED ISSUE #81: Improved error reports
**Is your feature request related to a problem? Please describe.**
At the moment, Luminol provides pretty basic error messages, especially related to the filesystem:
image
image

This makes it annoying to debug things. What file didn't exist? Did this happen just after the host filesystem was loaded, or after?

**Describe the solution you'd like**
Ideally we use some error type that allows us to provide additional context, all the way up the call chain.
```rs
// call site
texture_loader.load("Graphics/Characters", event_name).with_context("while loading an event")?;

// texture loader
fn load_texture(...) -> Result<Texture, Error> {
  filesystem.open_file(path).with_context(|| "while loading a texture")
}
// filesystem
fn open_file(...) -> Result<File, Error> {
  std::fs::open(path).with_context(|| format!("while opening {path}"))
}
```

**Describe alternatives you've considered**
miette looked appealing but I'm not sure how to use the API. anyhow has a `.with_context` method but that only seems to override any context provided.

### PR DESCRIPTION
**Pull request by white-axe**
**Connections**
* Closes #81
* rust-lang/rust#118168

**Description**
This pull request adds more detailed errors to the filesystem crate and switches the error reporting library from anyhow to color-eyre, which is basically the same thing as anyhow except it uses color-backtrace for error and panic reporting and supports a few extra features like adding extra messages (suggestions, etc.) to reports and printing spantraces from tracing-error.

Migrating from anyhow to color-eyre is easy:
* `anyhow::Error` -> `color_eyre::Report`
* `anyhow::Result` -> `color_eyre::Result`
* `anyhow::bail!` -> `color_eyre::eyre::bail!`
* `anyhow::anyhow!` -> `color_eyre::eyre::eyre!`
* `anyhow::Context` -> `color_eyre::eyre::WrapErr`
* `.context("Message")` -> `.wrap_err("Message")`
* `.with_context(|| "Message")` -> `.wrap_err_with(|| "Message")`

Errors are now shown both as toasts and as color-eyre formatted reports in the console. All other toast messages are redirected to the console as well.

Screenshot

There would be a backtrace shown in native builds. There are still no backtraces on WebAssembly because we're using the `panic_abort` panic handler instead of `panic_unwind`, which is not supported except in `no_std` environments (rust-lang/rust#118168). Theoretically it should be possible to get backtraces with `panic_abort` by passing `-Cforce-unwind-tables=yes` to rustc, but this doesn't seem to be supported for WebAssembly either.

The toast functions in crates/core/src/toasts.rs have been replaced with macros:

* `luminol_core::info!(update_state.toasts, "message")`
* `luminol_core::warn!(update_state.toasts, "message")`
* `luminol_core::basic!(update_state.toasts, "message")`

for generic toasts and `luminol_core::error!(update_state.toasts, report)` for errors where `report` is a `color_eyre::Report`. This is so that the log shows the actual location where a toast was created instead of showing every toast as being created in toasts.rs.

There's also a log window in native builds now that the error messages will show up in, since I don't expect most people will have an external console window open when running Luminol. It can be found at the bottom of the Debug menu in the top bar.

**Checklist**

- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`. If applicable, add:
  - [x] `--target wasm32-unknown-unknown`
- [x] Run `cargo build --release` 
- [x] If applicable, run `trunk build --release`

### CODE REVIEW

**Review by melody-rs — CHANGES_REQUESTED** [review]
After failing to open a project from the get started tab, Luminol thinks the project is opened
image

**Comment by white-axe** [comment]
I think this was a problem from before this pull request, but I'll fix it here anyways

**Comment by white-axe** [comment]
Alright, it should be fixed

**Review by melody-rs — APPROVED** [review]
Looks good to me!

**Review by melody-rs — APPROVED** [review]
Looks good to me!

**Pull request merged**
