### PR TITLE
Unify user interface crates

### PR DESCRIPTION
**Pull request by somedevfox**
**Connections**
None

**Description**
Luminol's user interface is rendered by three separate crates: `ui`, `modals` and `components`. It never made much sense to me, since all of them handle the same task. This pull request unifies these crates.

**Testing**
- Run `cargo run` or `trunk run` (depending on desired platform) and open the `About...` window. 

Additionally, I have measured compilation times between the [`dev`](https://github.com/Astrabit-ST/Luminol/tree/2165b809f6509eee51c30edf54463ca57cedd996) and [my](https://github.com/somedevfox/Luminol/tree/fc4939565554ec575c246f3bd8860470d36a96e7) branches by running `cargo build` in both. Both took the same amount of time to compile.

**Checklist**
- [x] Run `cargo fmt`.
- [x] Run `cargo clippy`. If applicable, add:
  - [ ] `--target wasm32-unknown-unknown -Z build-std=std,panic_abort`
- [x] Run `cargo build --release`
- [x] If applicable, run `trunk build --release`

### CODE REVIEW

**Review by white-axe — APPROVED** [review]
Looks good but please fix the "Build Trunk" build workflow at some point so that it actually uploads the web build to GitHub

**Comment by somedevfox** [comment]
Oh, I didn't know it was broken. Thank you for telling me.

**Review by melody-rs — COMMENTED** [review]
There's actually a reason why all of these crates were separate- I intended components and modals to be very general and unable to create tabs and windows.

Tabs and windows were combined into the same crate simply because of the MapInfos window- it needed to be able to create the map tab.

**Comment by melody-rs** [comment]
> Looks good but please fix the "Build Trunk" build workflow at some point so that it actually uploads the web build to GitHub

I'll go ahead and fix this

**Pull request merged**
