### PR TITLE
Implement drawing rectangular regions of tiles from the tilepicker

### PR DESCRIPTION
**Pull request by white-axe**

### CODE REVIEW

**Review by Speak2Erase — CHANGES_REQUESTED** [review]
It's possible to expand the tile selection past the bounds of the tilepicker, both horizontally, and vertically
luminol_vDSB4KiYCh

**Review by Speak2Erase — CHANGES_REQUESTED** [review]
When editing the event layer, the selection box is still displayed
luminol_LJtMJ4Wmel

**Review by Speak2Erase — CHANGES_REQUESTED** [review]
This may have been a bug from before this change, but it appears that the tilepicker displays the last layer of tiles incorrectly:
image

It's also not possible to select a tile at the bottom, trying to do so looks like this:
image

(For context, this is what the tilepicker should look like)
image

**Comment by white-axe** [comment]
Huh, that's weird, there must be something with that specific tilemap texture

**Comment by Speak2Erase** [comment]
Huh, you're right
It's 40.5 tiles tall (1296px)

**Comment by white-axe** [comment]
Ugh, okay, I'll pad the texture at the bottom

**Comment by Speak2Erase** [comment]
Could round the tileset size down ¯\\\_(ツ)\_/¯

**Review by Speak2Erase — APPROVED** [review]

**Pull request merged**
