### PR TITLE
Minor UI fix

### PR DESCRIPTION
**Pull request by white-axe**
When you create a new project, the path pushed to the list of recent projects was wrong, so you wouldn't have been able to open it from the recent projects. I just changed it to push the path of the new .lumproj instead of the path of the new project folder.

### CODE REVIEW

**Review by Speak2Erase — APPROVED** [review]

**Comment by Speak2Erase** [comment]
I'll probably be reworking the new project window soonish. I'm a little burnt out from luminol and my mental health is in the gutter, so I'm taking a little break

**Review by Speak2Erase — CHANGES_REQUESTED** [review]
Can you run rustfmt on your changes?

**Comment by white-axe** [comment]
Okay, one sec

**Comment by white-axe** [comment]
Hey, that's okay. Everyone needs a break every once in a while. I'll be going down the lists in the README and issues and seeing what I can do.

**Comment by Speak2Erase** [comment]
If you wanna help, take a look at the new-tilemap branch

It's pretty close to being finished and is way ahead of master (feature creep...)

**Review by Speak2Erase — APPROVED** [review]

**Pull request merged**
